/**
 * The hand-authored-docs specifier gate.
 *
 * `docs/reference/` is generated and has its own drift gate; the Diátaxis prose
 * quadrants (tutorial / how-to / explanation) are hand-written and compiled by
 * nothing, so a subpath that leaves `package.json` `exports` leaves the prose
 * behind still naming it. This module reads every `@demlik/tea/...` specifier
 * out of that prose and answers which ones the export map no longer carries.
 */

import { readdir, readFile } from "node:fs/promises";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

/** packages/tea — this file lives at src/docs/, two levels down. */
const PKG_ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
/** The hand-authored Diátaxis quadrants (everything under docs/ but the generated one). */
export const DOCS_DIR = join(PKG_ROOT, "docs");
/** Generated by `docs:reference`, gated by its own drift test — not this one's business. */
const GENERATED_DIR = join(DOCS_DIR, "reference");

/**
 * Every `@demlik/tea` specifier a markdown source names, bare package included
 * (as `.`, the export map's own spelling for the root door).
 */
const SPECIFIER = /@demlik\/tea(\/[A-Za-z0-9._/-]+)?/g;

/** One prose line naming a specifier the export map does not carry. */
export interface SpecifierHit {
  /** Repo-relative path of the offending page. */
  readonly file: string;
  /** 1-based line number. */
  readonly line: number;
  /** The specifier as the export map would spell it, e.g. `./authed-call`. */
  readonly subpath: string;
}

/** The export-map subpaths, as `package.json` spells them (`.`, `./subs`, …). */
export async function exportSubpaths(): Promise<ReadonlySet<string>> {
  const raw: unknown = JSON.parse(
    await readFile(join(PKG_ROOT, "package.json"), "utf8"),
  );
  const exports =
    typeof raw === "object" && raw !== null
      ? (raw as { exports?: unknown }).exports
      : undefined;
  if (typeof exports !== "object" || exports === null)
    throw new Error("package.json: `exports` is not an object");
  return new Set(Object.keys(exports));
}

/** Every hand-authored `.md` under `docs/`, in stable order. */
export async function handAuthoredPages(): Promise<readonly string[]> {
  const found: string[] = [];
  const walk = async (dir: string): Promise<void> => {
    for (const entry of await readdir(dir, { withFileTypes: true })) {
      const path = join(dir, entry.name);
      if (entry.isDirectory()) {
        if (path === GENERATED_DIR) continue;
        await walk(path);
      } else if (entry.name.endsWith(".md")) found.push(path);
    }
  };
  await walk(DOCS_DIR);
  return found.sort();
}

/**
 * Pure core: the specifiers `source` names that `subpaths` does not carry.
 * Split out from the filesystem so the guard can be proven to fire on text
 * that never has to exist on disk.
 */
export function unknownSpecifiersIn(
  file: string,
  source: string,
  subpaths: ReadonlySet<string>,
): readonly SpecifierHit[] {
  const hits: SpecifierHit[] = [];
  source.split("\n").forEach((text, index) => {
    for (const match of text.matchAll(SPECIFIER)) {
      const subpath = match[1] ? `.${match[1]}` : ".";
      if (!subpaths.has(subpath)) hits.push({ file, line: index + 1, subpath });
    }
  });
  return hits;
}

/** Every closed door the hand-authored quadrants still point a reader at. */
export async function collectSpecifierDrift(): Promise<
  readonly SpecifierHit[]
> {
  const subpaths = await exportSubpaths();
  const hits: SpecifierHit[] = [];
  for (const page of await handAuthoredPages()) {
    const source = await readFile(page, "utf8");
    hits.push(
      ...unknownSpecifiersIn(relative(PKG_ROOT, page), source, subpaths),
    );
  }
  return hits;
}

/** One hit per line, in the `file:line — subpath` shape a failure should read as. */
export function formatDrift(hits: readonly SpecifierHit[]): string {
  return hits
    .map(
      (h) =>
        `  ${h.file}:${h.line} — ${h.subpath} is not in package.json exports`,
    )
    .join("\n");
}
