/**
 * @packageDocumentation
 * `@demlik/structure-sweep` — the commands behind the `structure-sweep` bin, as functions. Each takes
 * its Jev client as an argument, so a caller (or a test) can run a sweep without the network.
 */

export {
  type ClusterOptions,
  ClusterRow,
  type ConsolidationPlan,
  type ExtractProposal,
  extractProposals,
  HelperPairRow,
  type MergeProposal,
  mergeProposals,
  renderConsolidation,
  type SmallFile,
} from "./consolidate/plan.js";
export {
  GroupsFile,
  GroupsFileError,
  groupsFileOf,
  readGroupsFile,
  writeGroupsFile,
} from "./groups/file.js";
export {
  type GroupList,
  type GroupListRow,
  type GroupView,
  listGroups,
  type OwnerView,
  type QuestionView,
  showGroup,
  UnknownGroupError,
} from "./groups/query.js";
export {
  DEFAULT_MODEL,
  fetchPost,
  httpJevClient,
  JevAskError,
  type JevClient,
} from "./jev.js";
export {
  type ArtifactKey,
  type ArtifactStore,
  artifactKey,
  canonicalJson,
  contentHash,
  memoryArtifactStore,
  runStage,
  type Stage,
  type StageArtifact,
  type StageInput,
  type StageRun,
  stageArtifactSchema,
} from "./lowering/artifact.js";
export {
  type Asker,
  askVerdict,
  type ChoiceQuestion,
  type ChoiceQuestions,
  type Judgement,
  labelsOf,
} from "./lowering/ask.js";
export {
  type Band,
  type CalibrateOptions,
  type Calibration,
  calibrate,
  confidenceBands,
  type DerivedFloor,
  expectedCalibrationError,
  type Scored,
  type UnreachableFloor,
} from "./lowering/calibration.js";
export {
  type Basis,
  derived,
  type Fact,
  type FactValue,
  factSchema,
  factValueSchema,
  SourceSpan,
  sourceSpan,
  type UnknownReason,
  unknownValue,
} from "./lowering/fact.js";
export {
  decide,
  type Enrich,
  factOf,
  type Gated,
  type GateItem,
  type GateOptions,
  type GateOutcome,
  type GatePolicy,
  gate,
  gateAll,
  gatePolicy,
  type HumanQueue,
  type HumanQueueEntry,
  type Retrying,
  type Settled,
} from "./lowering/gate.js";
export {
  askGroupVerdict,
  CandidateCluster,
  ClusterBasis,
  type ClusterDifference,
  ClusterMember,
  type ClusterQuestionState,
  ClusterRecord,
  type ClusterStatus,
  ConditionKey,
  type ConfirmOptions,
  clusterBranches,
  clusterId,
  clusterInput,
  clusterQuestionState,
  clusterStage,
  clusterStatus,
  conditionKey,
  confirmInput,
  confirmStage,
  DataBinding,
  DataEdgeRow,
  DENY,
  GROUP_CONFIRM_INSTRUCTIONS,
  GROUP_CONFIRM_STAGE,
  GROUP_VERDICT_CRITERIA,
  GROUP_VERDICTS,
  GROUPING_RULES,
  type GroupAnchor,
  type GroupCriterion,
  GroupingGraph,
  type GroupingRule,
  type GroupJudgement,
  GroupJudgementSchema,
  type GroupQueue,
  type GroupQueueEntry,
  type GroupVerdict,
  groupConfirmQuestion,
  groupQueue,
  type RuleGroup,
  readGroupingGraph,
  ruleGroups,
} from "./lowering/group.js";
export {
  type BoundaryCrossing,
  checkRatchet,
  emptyRuleGroupLedger,
  type RatchetVerdict,
  type Remeasure,
  type RemeasureInput,
  type RemeasureStores,
  type RemeasureVerdict,
  RuleGroupLedger,
  RuleGroupLedgerEntry,
  recordCollapse,
  remeasure,
  type SpecMember,
  specFiles,
  TaskSpec,
  taskSpecs,
} from "./lowering/handoff.js";
export {
  type EvaluateOptions,
  type Evaluation,
  type Exceeded,
  evaluate,
  flipRate,
  type GoldItem,
  type GoldSet,
  GoldSetError,
  type ItemScore,
  loadGoldSet,
  parseGoldSet,
  type ShipVerdict,
  shipVerdict,
  type Thresholds,
} from "./lowering/harness.js";
export {
  type Anchor,
  type AnchoringOptions,
  askBranchLabel,
  BRANCH_LABEL_CRITERIA,
  BRANCH_LABEL_INSTRUCTIONS,
  BRANCH_LABEL_STAGE,
  BRANCH_LABELS,
  type BranchJudgement,
  type BranchLabel,
  type BranchLabelOptions,
  type BranchLabelState,
  branchLabeller,
  branchLabelQuestion,
  branchLabelQuestions,
  branchLabelState,
  type Connect,
  type Criterion,
  type EvidenceItem,
  evaluateAnchoring,
  evidenceFirst,
  type LabelledBranch,
  labelBranches,
  type StateAtom,
} from "./lowering/label.js";
export {
  CONCEPT_KINDS,
  type ConceptKind,
  DEFAULT_LEXICON_FILE,
  draftPathOf,
  LEXICON_LABELS,
  type Lexicon,
  LexiconConfig,
  type LexiconDraft,
  LexiconEntry,
  LexiconError,
  type LexiconLabel,
  lexiconQuestion,
  loadLexicon,
  type ProposeLexiconOptions,
  parseLexicon,
  proposeLexicon,
  type Resolution,
  type ResolvedBranch,
  resolveBranch,
  resolveInput,
  resolveStage,
  type Site,
  type UnresolvedIdentifier,
  unresolvedIdentifiers,
  writeLexiconDraft,
} from "./lowering/lexicon.js";
export {
  type Atom,
  atomTerms,
  type Binding,
  type CallTerm,
  type CompareOperator,
  DEFAULT_LOGGING_ROOTS,
  type EqualityOperator,
  freeIdentifiers,
  GraphFunction,
  LOWERING_RULES,
  type LoweredBranch,
  type LoweringFileInput,
  LoweringGraph,
  type LoweringOptions,
  type LoweringRule,
  lowerFile,
  loweringInput,
  lowerStage,
  negate,
  type Outcome,
  outcomeTerms,
  readLoweringGraph,
  renderAtom,
  renderOutcome,
  renderTerm,
  type Term,
} from "./lowering/lower.js";
export {
  askOwner,
  type LayerLookup,
  type LayerRank,
  OWNER_INSTRUCTIONS,
  OWNER_REFS,
  OWNER_STAGE,
  Owner,
  OwnerCandidate,
  type OwnerJudgement,
  OwnerJudgementSchema,
  type OwnerOptions,
  type OwnerQuestionState,
  type OwnerQueue,
  type OwnerQueueEntry,
  OwnerRecord,
  type OwnerRef,
  ownerFacts,
  ownerInput,
  ownerQuestion,
  ownerQueue,
  ownerStage,
} from "./lowering/owner.js";
export { deriveRederived, REDERIVED } from "./lowering/rederived.js";
export {
  type BranchView,
  type CalleeView,
  type FunctionEvidence,
  type LabelResponsibilitiesOptions,
  labelResponsibilities,
  RESPONSIBILITY_ANSWERS,
  RESPONSIBILITY_INSTRUCTIONS,
  RESPONSIBILITY_STAGE,
  type Responsibilities,
  type Responsibility,
  type ResponsibilityAnswer,
  type ResponsibilityOptions,
  type ResponsibilityRequest,
  type ResponsibilityRequestsOptions,
  type ResponsibilityStage,
  type ResponsibilityState,
  responsibilityId,
  responsibilityQuestion,
  responsibilityRequests,
  responsibilityStage,
  responsibilityState,
  verdictOf,
} from "./lowering/responsibility.js";
export {
  type FeatureCounts,
  type Rollup,
  type RollupRow,
  rollup,
} from "./lowering/rollup.js";
export {
  type FunctionSummary,
  type Labeller,
  type LabelRecord,
  type LabelRequest,
  labelOf,
  type ReturnFact,
  type ReturnResolution,
  renderReturnFact,
  resolveReturns,
  type SccRun,
  type Summaries,
  type SummarizeOptions,
  summarize,
} from "./lowering/summarize.js";
export {
  type ApplyCommits,
  type ApplyReport,
  applyManifest,
} from "./move/apply.js";
export { planScope } from "./move/cli.js";
export { entryFiles } from "./move/entries.js";
export {
  GraphPull,
  Manifest,
  MoveRow,
  PinnedRow,
  ReviewRow,
  VerdictRow,
} from "./move/manifest.js";
export { applyMoves, type Move } from "./move/mover.js";
export {
  CONFIDENCE_FLOOR,
  type ImportEdge,
  type PlanInput,
  planManifest,
} from "./move/plan.js";
export {
  PAIR_VERDICTS,
  type PairAnswers,
  type PairQuestions,
  type PairVerdict,
  pairQuestions,
} from "./pairs/questions.js";
export {
  actionFor,
  countVerdicts,
  type PairRow,
  renderMarkdown,
} from "./pairs/report.js";
export {
  type PairsOptions,
  type PairsResult,
  type PairTarget,
  runPairs,
} from "./pairs/run.js";
export { renderScoreTable } from "./score/cli.js";
export { type HistoryOptions, readChangeSets } from "./score/history.js";
export {
  type ChangeSet,
  type ConfidenceShare,
  type FeatureScore,
  type Metric,
  type Prf,
  type ScoreOptions,
  type ScoreReport,
  ScoreRow,
  scoreCoChange,
} from "./score/score.js";
export {
  type SweepAnswers,
  type SweepQuestions,
  sweepQuestions,
} from "./sweep/questions.js";
export {
  type Nominate,
  runSweep,
  type SweepOptions,
  type SweepResult,
  type SweepRow,
  type SweepScopeResult,
  type SweepSelection,
} from "./sweep/run.js";
export {
  DEFAULT_CONFIG_FILE,
  loadVocabulary,
  parseVocabulary,
  type Vocabulary,
  VocabularyConfig,
  VocabularyError,
} from "./vocabulary.js";
